// User Reducer
export const GET_AUTHENTICATED_USER_DETAILS = "GET_AUTHENTICATED_USER_DETAILS";

// Authentication
export const SET_USER_AUTHENTICATED = "SET_USER_AUTHENTICATED";
export const SET_USER_UNAUTHENTICATED = "SET_USER_UNAUTHENTICATED";

// Facts
export const GET_ALL_FACTS = "GET_ALL_FACTS";
