export const GET_AUTHENTICATED_USER_DETAILS = "GET_AUTHENTICATED_USER_DETAILS";
export const GET_AUTHENTICATED_USER_DETAILS_ERROR =
	"GET_AUTHENTICATED_USER_DETAILS_ERROR";
export const GET_AUTHENTICATED_USER_DETAILS_LOADING =
	"GET_AUTHENTICATED_USER_DETAILS_LOADING";
export const GET_PROFILE = "GET_PROFILE";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const UPLOAD_IMAGE = "UPLOAD_IMAGE";
export const UPDATE_USER_DETAILS = "UPDATE_USER_DETAILS";
export const MARK_NOTIFICATIONS_READ = "MARK_NOTIFICATIONS_READ";
// Authentication
export const SET_USER_AUTHENTICATED = "SET_USER_AUTHENTICATED";
export const SET_USER_UNAUTHENTICATED = "SET_USER_UNAUTHENTICATED";

// Facts
export const GET_FACTS = "GET_FACTS";
export const GET_FACT = "GET_FACT";
export const CLEAR_FACTS = "CLEAR_FACTS";
export const CLEAR_FACT = "CLEAR_FACT";
export const ADD_COMMENT = "ADD_COMMENT";
export const ADD_LIKE = "ADD_LIKE";
export const REMOVE_LIKE = "REMOVE_LIKE";
export const ADD_FACT = "ADD_FACT";
